openapi: 3.0.3
info:
  title: DocIntel Document Processing API
  description: API contracts for Docling-based document ingestion
  version: 1.0.0

paths:
  /api/documents/{documentId}/process:
    post:
      summary: Trigger document processing with Docling
      description: |
        Initiates asynchronous document processing using Docling.
        The document must already be uploaded and associated with a chat.
      operationId: processDocument
      tags:
        - Document Processing
      parameters:
        - name: documentId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: ID of the uploaded document
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProcessingOptions'
      responses:
        '202':
          description: Processing started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessingStatusResponse'
        '404':
          description: Document not found
        '409':
          description: Document already processing or processed

  /api/documents/{documentId}/status:
    get:
      summary: Get document processing status
      operationId: getProcessingStatus
      tags:
        - Document Processing
      parameters:
        - name: documentId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Processing status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessingStatusResponse'
        '404':
          description: Document not found

  /api/documents/{documentId}/chunks:
    get:
      summary: Get document chunks
      description: Returns all semantic chunks generated from the document
      operationId: getDocumentChunks
      tags:
        - Document Chunks
      parameters:
        - name: documentId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: contentType
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/ContentType'
          description: Filter by content type
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 20
            maximum: 100
      responses:
        '200':
          description: List of document chunks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChunkListResponse'
        '404':
          description: Document not found
        '400':
          description: Document not yet processed

  /api/documents/{documentId}/reprocess:
    post:
      summary: Re-process document with Docling
      description: |
        Triggers re-processing of an already processed document.
        Useful when Docling version is updated or chunking config changes.
        Existing chunks are deleted and recreated.
      operationId: reprocessDocument
      tags:
        - Document Processing
      parameters:
        - name: documentId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProcessingOptions'
      responses:
        '202':
          description: Re-processing started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessingStatusResponse'
        '404':
          description: Document not found

components:
  schemas:
    ProcessingOptions:
      type: object
      properties:
        chunkingStrategy:
          type: string
          enum: [HIERARCHICAL, HYBRID]
          default: HYBRID
          description: Chunking strategy to use
        maxTokens:
          type: integer
          minimum: 100
          maximum: 8000
          default: 2000
          description: Maximum tokens per chunk
        generateHypotheticalQuestions:
          type: boolean
          default: true
          description: Whether to generate hypothetical questions for RAG

    ProcessingStatusResponse:
      type: object
      required:
        - documentId
        - status
      properties:
        documentId:
          type: string
          format: uuid
        status:
          $ref: '#/components/schemas/ProcessingStatus'
        chunkCount:
          type: integer
          description: Number of chunks generated (when completed)
        processingError:
          type: string
          description: Error message (when failed)
        processedAt:
          type: string
          format: date-time
          description: Completion timestamp
        processorVersion:
          type: string
          description: Docling version used

    ProcessingStatus:
      type: string
      enum:
        - PENDING
        - PROCESSING
        - COMPLETED
        - FAILED

    ContentType:
      type: string
      enum:
        - TEXT
        - TABLE
        - LIST
        - CODE
        - HEADING
        - MIXED

    DocumentChunk:
      type: object
      required:
        - id
        - content
        - contentType
        - position
        - tokenCount
      properties:
        id:
          type: string
          format: uuid
        content:
          type: string
          description: Markdown content of the chunk
        contentType:
          $ref: '#/components/schemas/ContentType'
        position:
          type: integer
          description: Order within document
        sectionHeading:
          type: string
          description: Parent section heading
        headingLevel:
          type: integer
          minimum: 1
          maximum: 6
          description: Depth in document hierarchy
        tokenCount:
          type: integer
        createdAt:
          type: string
          format: date-time

    ChunkListResponse:
      type: object
      required:
        - chunks
        - totalCount
        - page
        - size
      properties:
        chunks:
          type: array
          items:
            $ref: '#/components/schemas/DocumentChunk'
        totalCount:
          type: integer
        page:
          type: integer
        size:
          type: integer
        hasMore:
          type: boolean

tags:
  - name: Document Processing
    description: Operations for processing documents with Docling
  - name: Document Chunks
    description: Operations for accessing document chunks
